### PR TITLE
Add support for exec resources

### PR DESCRIPTION
**Pull request by Phil-Friderici**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Thanks @Phil-Friderici 

Could you please document this in the README with examples.

**Comment by Phil-Friderici** [comment]
here we go, now with added docs & examples

**Comment by Phil-Friderici** [comment]
thanks a lot :)

**Comment by ghoneycutt** [comment]
thank you!

**Comment by ghoneycutt** [comment]
Released in v1.12.0

**Pull request merged**
